name = "DelayDiffEq"
uuid = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
version = "5.68.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DDEProblemLibrary = "f42792ee-6ffc-4e2a-ae83-8ee2f22de800"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
FastBroadcast = "7034ab61-46d4-4ed7-9d0f-46aef9175898"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
OrdinaryDiffEqDifferentiation = "4302a76b-040a-498a-8c04-15b101fed76b"
OrdinaryDiffEqFunctionMap = "d3585ca7-f5d3-4ba6-8057-292ed1abd90f"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLLogging = "a6db7da4-7206-11f0-1eab-35f2a5dbe1d1"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Aqua = "0.8.14"
ArrayInterface = "7"
ConcreteStructs = "0.2.3"
DDEProblemLibrary = "0.1.4"
DataStructures = "0.18, 0.19"
DiffEqBase = "6.187"
DiffEqCallbacks = "4.12.0"
DiffEqDevTools = "2.49.0"
ExplicitImports = "1.15.0"
FastBroadcast = "0.3.5"
FiniteDiff = "2.29.0"
ForwardDiff = "1.0.1"
LinearAlgebra = "1"
LinearSolve = "3.58.0"
Logging = "1"
OrdinaryDiffEq = "6.69"
OrdinaryDiffEqCore = "3.2"
OrdinaryDiffEqDefault = "1.9"
OrdinaryDiffEqDifferentiation = "2"
OrdinaryDiffEqFunctionMap = "1.6"
OrdinaryDiffEqNonlinearSolve = "1.16"
OrdinaryDiffEqRosenbrock = "1.19"
Printf = "1"
RecursiveArrayTools = "3"
Reexport = "1.0"
SafeTestsets = "0.1.0"
SciMLBase = "2.115.0"
SciMLLogging = "1.4.0"
SimpleNonlinearSolve = "2"
SymbolicIndexingInterface = "0.3.36"
Unitful = "1.28.0"
julia = "1.10"
